version: '2.4'
services:
  hmc-hmi-outbound-adapter-api:
    image: "${HMC_HMI_OUTBOUND_ADAPTER_USE_LOCAL-hmctspublic.azurecr.io/}hmc/hmi-outbound-adapter:${HMC_HMI_OUTBOUND_ADAPTER_TAG:-latest}"
    environment:
      REFORM_SERVICE_NAME: hmc-hmi-outbound-adapter-api
      REFORM_TEAM: hmi
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4558:4558
    networks:
      - hmc-network

  hmc-hmi-inbound-adapter-api:
    image: "${HMC_HMI_INBOUND_ADAPTER_USE_LOCAL-hmctspublic.azurecr.io/}hmc/hmi-inbound-adapter:${HMC_HMI_INBOUND_ADAPTER_TAG:-latest}"
    environment:
      REFORM_SERVICE_NAME: hmc-hmi-inbound-adapter-api
      REFORM_TEAM: hmi
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4559:4559
    networks:
      - hmc-network

networks:
  hmc-network:
    external: true
