version: '2.4'
services:
  hmc-hmi-outbound-adapter:
    image: "${HMC_HMI_OUTBOUND_ADAPTER_USE_LOCAL-hmctspublic.azurecr.io/}hmc/hmi-outbound-adapter:${HMC_HMI_OUTBOUND_ADAPTER_TAG:-latest}"
    container_name: hmi-outbound-adapter
    environment:
      SERVER_PORT: 4558
      REFORM_SERVICE_NAME: hmc-hmi-outbound-adapter
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4558:4558
    depends_on:
      - hmc-wiremock
    networks:
      - hmc-network

  hmc-hmi-inbound-adapter:
    image: "${HMC_HMI_INBOUND_ADAPTER_USE_LOCAL-hmctspublic.azurecr.io/}hmc/hmi-inbound-adapter:${HMC_HMI_INBOUND_ADAPTER_TAG:-latest}"
    container_name: hmi-inbound-adapter
    environment:
      SERVER_PORT: 4559
      REFORM_SERVICE_NAME: hmc-hmi-inbound-adapter
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4559:4559
    networks:
      - hmc-network

  hmc-wiremock:
    image: rodolpheche/wiremock
    container_name: hmc-wiremock
    volumes:
      - ./../resources/wiremock:/home/wiremock:rw
    ports:
      - 4459:8080
    networks:
      - hmc-network

networks:
  hmc-network:
    external: true
